# Feature Engineering

In [77]:
# import libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

#### Acces to drive to get data

In [78]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#### Reading and explore data

In [79]:
data=pd.read_csv('/content/drive/MyDrive/data_without_preproed_dates.csv')
data.head()

,Unnamed: 0,category_code,status,founded_at,country_code,funding_total_usd,first_milestone_at,last_milestone_at,milestones,relationships,created_at,updated_at,lat,lng
0,0,web,operating,2005-10-17,USA,39750000.0,2010-09-05,2013-09-18,5.0,17.0,2007-05-25 06:51:27,2013-04-13 03:29:00,47.606209,-122.332071
1,1,games_video,acquired,2011-01-01,USA,2564500.0,2012-01-01,2012-01-01,1.0,6.0,2007-05-31 21:11:51,2008-05-23 23:23:14,34.021122,-118.396467
2,2,games_video,acquired,2011-01-01,USA,2564500.0,2003-02-01,2011-09-23,4.0,12.0,2007-08-06 23:52:45,2013-11-04 02:09:48,37.562992,-122.325525
3,3,network_hosting,operating,2008-07-26,USA,2564500.0,2012-01-01,2012-01-01,1.0,1.0,2008-08-24 16:51:57,2008-09-06 14:19:18,39.768403,-77.036871
4,4,games_video,operating,2008-07-26,USA,2564500.0,2012-01-01,2012-01-01,1.0,1.0,2008-08-24 17:10:34,2008-09-06 14:19:18,39.768403,-77.036871

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196553 entries, 0 to 196552
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Unnamed: 0          196553 non-null  int64
 1   category_code       196553 non-null  object
 2   status              196553 non-null  object
 3   founded_at          196553 non-null  object
 4   country_code        196553 non-null  object
 5   funding_total_usd   196553 non-null  float64
 6   first_milestone_at  196553 non-null  object
 7   last_milestone_at   196553 non-null  object
 8   milestones          196553 non-null  float64
 9   relationships       196553 non-null  float64
 10  created_at          196553 non-null  object
 11  updated_at          196553 non-null  object
 12  lat                 196553 non-null  float64
 13  lng                 196553 non-null  float64
dtypes: float64(5), int64(1), object(8)
memory usage: 21.0+ MB

In [81]:
data.describe()

,Unnamed: 0,funding_total_usd,milestones,relationships,lat,lng
count,196553.000000,1.965530e+05,196553.000000,196553.000000,196553.000000,196553.000000
mean,98276.000000,4.302010e+06,1.093028,2.221818,38.828195,-66.408326
std,56740.108067,2.587209e+07,0.382082,7.443372,10.167523,47.383031
min,0.000000,2.910000e+02,1.000000,1.000000,-50.942326,-159.497746
25%,49138.000000,2.564500e+06,1.000000,1.000000,39.768403,-77.036871
50%,98276.000000,2.564500e+06,1.000000,1.000000,39.768403,-77.036871
75%,147414.000000,2.564500e+06,1.000000,2.000000,39.768403,-77.036871
max,196552.000000,5.700000e+09,9.000000,1189.000000,77.553604,176.212549

## Check missing values

In [82]:
for col,null in enumerate(data.isnull().sum()):
  print(data.columns.values[col]," :",np.int(null/len(data)*100))

Unnamed: 0  : 0
category_code  : 0
status  : 0
founded_at  : 0
country_code  : 0
funding_total_usd  : 0
first_milestone_at  : 0
last_milestone_at  : 0
milestones  : 0
relationships  : 0
created_at  : 0
updated_at  : 0
lat  : 0
lng  : 0

<ipython-input-82-36906a027d68>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data.columns.values[col]," :",np.int(null/len(data)*100))

In [83]:
# # feature eng
date_list=['created_at','first_milestone_at','last_milestone_at','updated_at','founded_at']


for date_col in date_list :
  # estimate missing dates
  # data[date_col].interpolate(method='linear', inplace=True)
  data[date_col]         = pd.to_datetime(data[date_col])
  data['year'+date_col]  = data[date_col].dt.year
  data['month'+date_col] = data[date_col].dt.month
  data['day'+date_col]   = data[date_col].dt.day
  data.drop(inplace =True,columns=date_col,axis=1)

In [84]:
data.head()

,Unnamed: 0,category_code,status,country_code,funding_total_usd,milestones,relationships,lat,lng,yearcreated_at,...,dayfirst_milestone_at,yearlast_milestone_at,monthlast_milestone_at,daylast_milestone_at,yearupdated_at,monthupdated_at,dayupdated_at,yearfounded_at,monthfounded_at,dayfounded_at
0,0,web,operating,USA,39750000.0,5.0,17.0,47.606209,-122.332071,2007,...,5,2013,9,18,2013,4,13,2005,10,17
1,1,games_video,acquired,USA,2564500.0,1.0,6.0,34.021122,-118.396467,2007,...,1,2012,1,1,2008,5,23,2011,1,1
2,2,games_video,acquired,USA,2564500.0,4.0,12.0,37.562992,-122.325525,2007,...,1,2011,9,23,2013,11,4,2011,1,1
3,3,network_hosting,operating,USA,2564500.0,1.0,1.0,39.768403,-77.036871,2008,...,1,2012,1,1,2008,9,6,2008,7,26
4,4,games_video,operating,USA,2564500.0,1.0,1.0,39.768403,-77.036871,2008,...,1,2012,1,1,2008,9,6,2008,7,26

In [85]:
new_data=data[['country_code','category_code']]

In [86]:
data[['country_code','status','category_code']].isnull().sum()

country_code     0
status           0
category_code    0
dtype: int64

In [87]:
data.drop(columns=['country_code','Unnamed: 0','category_code'],inplace=True)

In [88]:
new_data=pd.get_dummies(new_data)

In [89]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196553 entries, 0 to 196552
Columns: 217 entries, country_code_AFG to category_code_web
dtypes: uint8(217)
memory usage: 40.7 MB

In [90]:
new_data[new_data['country_code_AFG']==1]

,country_code_AFG,country_code_AGO,country_code_AIA,country_code_ALB,country_code_AND,country_code_ANT,country_code_ARA,country_code_ARE,country_code_ARG,country_code_ARM,...,category_code_real_estate,category_code_search,category_code_security,category_code_semiconductor,category_code_social,category_code_software,category_code_sports,category_code_transportation,category_code_travel,category_code_web
30812,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80338,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180502,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
182149,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
182393,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
182912,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
188197,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
195328,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

### final data

In [91]:
final_data=pd.concat([data,new_data], axis=1)
final_data.head()

,status,funding_total_usd,milestones,relationships,lat,lng,yearcreated_at,monthcreated_at,daycreated_at,yearfirst_milestone_at,...,category_code_real_estate,category_code_search,category_code_security,category_code_semiconductor,category_code_social,category_code_software,category_code_sports,category_code_transportation,category_code_travel,category_code_web
0,operating,39750000.0,5.0,17.0,47.606209,-122.332071,2007,5,25,2010,...,0,0,0,0,0,0,0,0,0,1
1,acquired,2564500.0,1.0,6.0,34.021122,-118.396467,2007,5,31,2012,...,0,0,0,0,0,0,0,0,0,0
2,acquired,2564500.0,4.0,12.0,37.562992,-122.325525,2007,8,6,2003,...,0,0,0,0,0,0,0,0,0,0
3,operating,2564500.0,1.0,1.0,39.768403,-77.036871,2008,8,24,2012,...,0,0,0,0,0,0,0,0,0,0
4,operating,2564500.0,1.0,1.0,39.768403,-77.036871,2008,8,24,2012,...,0,0,0,0,0,0,0,0,0,0

In [92]:
final_data.isnull().sum()

status                          0
funding_total_usd               0
milestones                      0
relationships                   0
lat                             0
                               ..
category_code_software          0
category_code_sports            0
category_code_transportation    0
category_code_travel            0
category_code_web               0
Length: 238, dtype: int64

In [93]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196553 entries, 0 to 196552
Columns: 238 entries, status to category_code_web
dtypes: float64(5), int64(15), object(1), uint8(217)
memory usage: 72.2+ MB

In [94]:
data.to_csv('/content/drive/MyDrive/data_with_dates.csv')